### ISSUE TITLE
Swift example: AnonymizationResponse can't decode result

### ISSUE THREAD

**Issue by joyofscripting** [wassafr/wis-api-samples#1]
The class AnonymizationResponse following the Decodable protocol cannot decode the Result retrieved from the Anonymization API service.

The reason is that in the API result the dictionary keys in the JSON structure are "output_media" and "output_json".  But the property names of the class are "outputMedia" and "outputJson". Therefore the decoder fails.

Once I changed the property names of the AnonymizationResponse to "output_media" and "output_json" everything worked fine.

**Comment by wassafr** [comment]
Hi
Thank you for submitting this issue.
We're looking into it and will provide a fix ASAP if we can reproduce the issue

**Comment by ralleeWassa** [comment]
Hi.

We have checked your issue. You just miss a little configuration line in your JsonDecoder.
Since the properties need to be correctly named in the models, the configuration of the API in snake case is done in the JsonDecoder.

You just have to put this line after the creation of your decoder:

`decoder.keyDecodingStrategy = .convertFromSnakeCase`

Feel free to discuss if you think it's a wrong choice. We are always listening for improving our product. 
Also, feel free to fork and improve our example, pull requests are welcome. 

Have a good day

**Comment by joyofscripting** [comment]
Hi,

Thank you very much for looking into it. Yes, now I can see it in the WisService class:

`class WisService {
  
  let encoder = JSONEncoder()
  let decoder = JSONDecoder()
  static var token: Token?
  
  init() {
    decoder.keyDecodingStrategy = .convertFromSnakeCase
  }`

And after preparing the decoder in my code as well, it works like a charm!

Best regards from Berlin,

Martin
